# Generated by Django 6.0.4 on 2026-04-29 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Chamado')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em Andamento', 'Em Andamento'), ('Resolvido', 'Resolvido'), ('Fechado', 'Fechado')], default='Aberto', max_length=20)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Normal', 'Normal'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], default='Normal', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
