# Generated by Django 6.0.4 on 2026-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos_chamados/', verbose_name='Anexo (Print do Erro)'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos_comentarios/', verbose_name='Anexo'),
        ),
    ]
