# Generated by Django 6.0.4 on 2026-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_chamado_anexo_comentario_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('Software', 'Software/Sistemas'), ('Hardware', 'Hardware/Periféricos'), ('Rede', 'Rede/Internet'), ('Acessos', 'Acessos e Senhas'), ('Outros', 'Outros')], default='Outros', max_length=30),
        ),
    ]
