# Generated by Django 6.0.4 on 2026-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_chamado_fechado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
