# Generated by Django 6.0.4 on 2026-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_chamado_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
    ]
